name: Validate

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    name: Validate HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        name: "HACS Validation"
        with:
          category: integration
      - uses: home-assistant/actions/hassfest@master
        name: "HA Validation"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - uses: actions/checkout@v4
      - uses: python-semantic-release/python-semantic-release@v9.8.9
        with:
          github_token: ${{ secrets.GH_TOKEN }}
